name: CI

on:
  push:
    branches:
      - main
      - dev
      - testing
  pull_request:
    branches:
      - main
      - dev
      - testing

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libx11-dev libxcursor-dev libxrandr-dev libxi-dev libgl1-mesa-dev

      - name: Build
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && cmake --build build -- -j

      - name: Run tests
        run: cmake --build build --target testing -j && ctest --test-dir build --output-on-failure
